/**
 * P4.2 — Public glossary: 200+ FX / Moroccan regulatory / banking terms.
 * Each term has a slug, a short definition (FR + EN), and a category.
 * Used for SEO long-tail traffic and internal linking from blog posts.
 */

export type GlossaryCategory =
  | 'fx-basics'
  | 'fx-advanced'
  | 'mad-specific'
  | 'regulation-oc'
  | 'risk-management'
  | 'banking-morocco'
  | 'monetary-policy'
  | 'instruments';

export interface GlossaryTerm {
  slug: string;
  term: string;
  shortFr: string;
  shortEn: string;
  longFr: string;
  longEn: string;
  category: GlossaryCategory;
  related: string[]; // slugs
  examples?: string[];
}

export const GLOSSARY_CATEGORIES: Record<GlossaryCategory, { label: string; icon: string }> = {
  'fx-basics':         { label: 'Notions FX de base',      icon: '📚' },
  'fx-advanced':       { label: 'FX avancé',                icon: '🎓' },
  'mad-specific':      { label: 'Spécifique au MAD',       icon: '🇲🇦' },
  'regulation-oc':     { label: 'Réglementation OC',        icon: '⚖️' },
  'risk-management':   { label: 'Gestion des risques',     icon: '🛡️' },
  'banking-morocco':   { label: 'Banque au Maroc',         icon: '🏦' },
  'monetary-policy':   { label: 'Politique monétaire',     icon: '🏛️' },
  'instruments':       { label: 'Instruments financiers',  icon: '💱' },
};

export const GLOSSARY: GlossaryTerm[] = [
  // === FX BASICS ===
  { slug: 'taux-de-change', term: 'Taux de change', shortFr: 'Prix d\'une devise exprimée dans une autre devise.', shortEn: 'Price of one currency expressed in another.', longFr: 'Le taux de change est le prix relatif de deux devises. Il détermine combien d\'unités d\'une devise (la devise de contrepartie) sont nécessaires pour acheter une unité de l\'autre devise (la devise de base). Le MAD est la devise de base pour le dirham marocain.', longEn: 'An exchange rate is the relative price of two currencies. It determines how many units of one currency (the quote currency) are needed to buy one unit of the other (the base currency). The MAD is the base currency for the Moroccan dirham.', category: 'fx-basics', related: ['pip', 'cross-rate'], examples: ['EUR/MAD = 10.85 signifie qu\'1 EUR = 10.85 MAD'] },
  { slug: 'pip', term: 'Pip', shortFr: 'Plus petite variation standard d\'un taux de change (0.0001).', shortEn: 'Smallest standard change in an exchange rate (0.0001).', longFr: 'Un pip est la 4ème décimale d\'un taux de change (0.0001). Pour les paires JPY, 1 pip = 0.01. Pips sont utilisés pour mesurer les mouvements de prix et calculer les gains/pertes.', longEn: 'A pip is the 4th decimal of a quoted exchange rate (0.0001). For JPY pairs, 1 pip = 0.01. Pips measure price movements and P&L.', category: 'fx-basics', related: ['taux-de-change', 'forward-points'], examples: ['EUR/USD passant de 1.0850 à 1.0851 = +1 pip'] },
  { slug: 'cross-rate', term: 'Cross rate / Taux croisé', shortFr: 'Taux entre deux devises calculé via une devise pivot (souvent USD).', shortEn: 'Rate between two currencies calculated via a pivot (often USD).', longFr: 'Un cross rate est un taux de change entre deux devises qui ne contient pas le dollar US. Exemple : EUR/JPY, GBP/CHF. Il est calculé à partir des taux par rapport à l\'USD.', longEn: 'A cross rate is an exchange rate between two currencies that does not include the USD. Example: EUR/JPY, GBP/CHF. It is derived from rates against USD.', category: 'fx-basics', related: ['taux-de-change', 'pip'] },
  { slug: 'bid-ask', term: 'Bid / Ask', shortFr: 'Bid = prix d\'achat, Ask = prix de vente. Spread = Ask − Bid.', shortEn: 'Bid = buy price, Ask = sell price. Spread = Ask − Bid.', longFr: 'Le bid est le prix auquel le marché (ou votre banque) achète la devise de base. L\'ask est le prix auquel il la vend. Le spread est la rémunération du teneur de marché.', longEn: 'The bid is the price at which the market (or your bank) buys the base currency. The ask is the price at which it sells. The spread is the market-maker\'s compensation.', category: 'fx-basics', related: ['pip', 'spread'], examples: ['EUR/MAD bid=10.84, ask=10.86 → spread = 2 pips = 0.18%'] },
  { slug: 'spread', term: 'Spread', shortFr: 'Écart entre prix bid et ask, exprimé en pips ou %.', shortEn: 'Difference between bid and ask, in pips or %.', longFr: 'Le spread est l\'écart bid-ask. Il représente le coût de transaction implicite. Plus le spread est serré, plus le marché est liquide.', longEn: 'The spread is the bid-ask difference. It is the implicit transaction cost. Tighter spread = more liquid market.', category: 'fx-basics', related: ['bid-ask', 'pip'], examples: ['EUR/MAD billet 200-220 pips vs virement 10-15 pips'] },
  { slug: 'spot', term: 'Spot', shortFr: 'Transaction au cours du jour, livraison T+2 standard.', shortEn: 'Transaction at current rate, T+2 standard delivery.', longFr: 'Le spot est la transaction de change au cours du jour, avec livraison standard T+2 (2 jours ouvrés). Pour le MAD, c\'est la référence quotidienne publiée par Bank Al-Maghrib à 12h30 (intraday) et 16h15 (clôture).', longEn: 'A spot is a foreign exchange transaction at the current rate, with T+2 standard delivery (2 business days). For MAD, the daily reference is published by Bank Al-Maghrib at 12:30 (intraday) and 16:15 (close).', category: 'fx-basics', related: ['taux-de-change', 't2', 'fixing'] },
  { slug: 't2', term: 'T+2', shortFr: 'Date de valeur spot = 2 jours ouvrés après la transaction.', shortEn: 'Spot value date = 2 business days after the trade.', longFr: 'Le T+2 est la convention standard pour la livraison des transactions spot. Pour une transaction le mardi, la livraison a lieu le jeudi. Si le T+2 tombe un jour férié (weekend ou jour férié MA), on reporte au jour ouvré suivant.', longEn: 'T+2 is the standard convention for spot value date. For a Tuesday trade, delivery happens on Thursday. If T+2 falls on a holiday (weekend or MA public holiday), it rolls to the next business day.', category: 'fx-basics', related: ['spot', 'holiday-calendar'] },
  { slug: 'virement-billet', term: 'Virement vs Billet', shortFr: 'Virement = wire transfer, billets = banknotes. Spreads très différents.', shortEn: 'Virement = wire, billets = banknotes. Very different spreads.', longFr: 'Le virement (wire transfer) est une opération scripturale entre banques — spread typique 0.05-0.15%. Le billet (banknotes) implique un transport physique, assurance, immobilisation — spread typique 1-3%.', longEn: 'A virement (wire) is a book entry between banks — typical spread 0.05-0.15%. Bills (banknotes) involve physical transport, insurance, immobilisation — typical spread 1-3%.', category: 'fx-basics', related: ['spread'] },

  // === FX ADVANCED ===
  { slug: 'cip', term: 'CIP (Covered Interest Parity)', shortFr: 'Parité de taux d\'intérêt couverte : F = S × (1+rd×T) / (1+rf×T).', shortEn: 'Covered interest parity: F = S × (1+rd×T) / (1+rf×T).', longFr: 'La CIP est une relation d\'arbitrage sans risque : le taux forward doit refléter le différentiel de taux d\'intérêt entre les deux devises, sinon un arbitrage est possible. F = S × (1 + r_d × T) / (1 + r_f × T).', longEn: 'CIP is a no-arbitrage relation: the forward rate must reflect the interest rate differential, otherwise arbitrage is possible. F = S × (1 + r_d × T) / (1 + r_f × T).', category: 'fx-advanced', related: ['forward', 'taux-sans-arb'], examples: ['EUR/MAD spot 10.85, r_d MAD=2.5%, r_f EUR=2.25%, T=0.25 → F ≈ 10.851'] },
  { slug: 'xcs', term: 'Cross-Currency Basis (XCS)', shortFr: 'Écart entre CIP théorique et swap FX réel, dû au risque de contrepartie.', shortEn: 'Gap between theoretical CIP and actual FX swap, due to counterparty risk.', longFr: 'La base de change (XCS) mesure l\'écart entre le taux forward théorique (CIP) et le taux forward réel observable sur le marché des swaps. Depuis 2008, EUR/USD basis peut atteindre +30 bps. Le MAD, devise gérée, a un basis proche de 0.', longEn: 'The cross-currency basis (XCS) measures the gap between the theoretical CIP forward and the actual swap-market forward. Since 2008, the EUR/USD basis can reach +30 bps. The MAD, a managed currency, has a basis near 0.', category: 'fx-advanced', related: ['cip', 'forward'] },
  { slug: 'forward', term: 'Forward', shortFr: 'Contrat de change à terme avec livraison et taux fixés aujourd\'hui.', shortEn: 'Forward contract: rate and delivery date fixed today.', longFr: 'Un forward est un accord bilatéral d\'échanger deux devises à un taux et une date future convenus aujourd\'hui. Pas d\'échange initial. Régulé par la Circ. OC 01/2024 pour les entreprises marocaines.', longEn: 'A forward is a bilateral agreement to exchange two currencies at a rate and future date fixed today. No initial exchange. Regulated by Circ. OC 01/2024 for Moroccan corporates.', category: 'fx-advanced', related: ['cip', 'forward-points', 'swap'], examples: ['Forward EUR/MAD 3M : taux fixé aujourd\'hui, livraison dans 3 mois'] },
  { slug: 'forward-points', term: 'Forward points / Points de swap', shortFr: 'Différence entre forward et spot, exprimée en pips.', shortEn: 'Difference between forward and spot, in pips.', longFr: 'Les forward points représentent l\'écart entre le taux forward et le taux spot. F - S. Ils sont positifs si la devise domestique a un taux directeur plus élevé (carry trade positif) et négatifs sinon.', longEn: 'Forward points are the difference between the forward and spot rates. F - S. They are positive if the domestic currency has a higher policy rate (positive carry) and negative otherwise.', category: 'fx-advanced', related: ['forward', 'cip', 'pip'] },
  { slug: 'swap', term: 'Swap de change', shortFr: 'Double forward simultané : achat spot + vente forward (ou inverse).', shortEn: 'Simultaneous dual forward: buy spot + sell forward (or reverse).', longFr: 'Un swap de change est la combinaison d\'un spot et d\'un forward inverse. Utilisé pour rouler une position (rollover) ou pour swapper temporairement une devise sans livraison.', longEn: 'An FX swap is a combination of a spot and a reverse forward. Used to roll a position or to temporarily swap a currency without delivery.', category: 'fx-advanced', related: ['forward', 'rollover'] },
  { slug: 'rollover', term: 'Rollover / Prorogation', shortFr: 'Reconduction d\'un forward à une nouvelle échéance.', shortEn: 'Extending a forward to a new maturity date.', longFr: 'Le rollover consiste à dénouer un forward arrivant à maturité et à en booker un nouveau pour une période ultérieure. Le coût est la différence de points de swap entre les deux maturités.', longEn: 'A rollover unwinds a forward at maturity and books a new one for a later period. The cost is the swap points difference between the two maturities.', category: 'fx-advanced', related: ['forward', 'swap'] },
  { slug: 'option-vanilla', term: 'Option vanilla', shortFr: 'Droit (non obligation) d\'acheter/vendre à un strike donné.', shortEn: 'Right (not obligation) to buy/sell at a given strike.', longFr: 'Une option vanilla donne à l\'acheteur le droit, mais pas l\'obligation, d\'acheter (call) ou vendre (put) une devise à un prix d\'exercice (strike) à une date future. Coût = prime.', longEn: 'A vanilla option gives the buyer the right, but not the obligation, to buy (call) or sell (put) a currency at a strike price on a future date. Cost = premium.', category: 'fx-advanced', related: ['forward', 'instruments'] },
  { slug: 'option-exotique', term: 'Option exotique', shortFr: 'Option à payoff non-standard (knock-out, barrier, digital, etc.).', shortEn: 'Non-standard payoff option (knock-out, barrier, digital...).', longFr: 'Les options exotiques ont des caractéristiques de payoff non-standard (barrier, knock-out, lookback, digital). INTERDITES par la Circ. OC 01/2024 pour les entreprises marocaines.', longEn: 'Exotic options have non-standard payoff characteristics (barrier, knock-out, lookback, digital). PROHIBITED by Circ. OC 01/2024 for Moroccan corporates.', category: 'fx-advanced', related: ['option-vanilla', 'circ-oc-01-2024'] },
  { slug: 'ndf', term: 'NDF (Non-Deliverable Forward)', shortFr: 'Forward sans livraison physique, réglé en différentiel.', shortEn: 'Forward without physical delivery, settled in differential.', longFr: 'Un NDF est un forward sur une devise non convertible (historiquement le MAD avant 2018) qui se règle en cash, sans livraison de devise. INTERDIT pour le MAD depuis la convertibilité du compte capital (2018).', longEn: 'An NDF is a forward on a non-convertible currency (historically MAD pre-2018) cash-settled without currency delivery. PROHIBITED for MAD since capital account convertibility (2018).', category: 'fx-advanced', related: ['forward', 'convertibilite'] },
  { slug: 'volatilite-implicite', term: 'Volatilité implicite', shortFr: 'Vol future attendue par le marché, dérivée des prix d\'options.', shortEn: 'Future vol expected by the market, derived from option prices.', longFr: 'La volatilité implicite (VI) est la volatilité annualisée que le marché "price" pour une devise à une échéance donnée. Elle se déduit des primes d\'options via Black-Scholes. Une VI élevée = marché stressé.', longEn: 'Implied volatility (IV) is the annualised vol the market prices in for a currency at a given maturity. It is derived from option premiums via Black-Scholes. High IV = stressed market.', category: 'fx-advanced', related: ['option-vanilla', 'vol-surface'] },
  { slug: 'vol-surface', term: 'Surface de volatilité', shortFr: 'VI par strike et par maturité — visualise la "peur" du marché.', shortEn: 'IV by strike and maturity — visualises market "fear".', longFr: 'La surface de volatilité (vol surface) est la matrice VI pour chaque combinaison strike × maturité. Le skew (asymétrie) indique si le marché se protège plus à la hausse qu\'à la baisse.', longEn: 'The volatility surface is the IV matrix for each strike × maturity combination. The skew indicates whether the market is hedging more for upside than downside moves.', category: 'fx-advanced', related: ['volatilite-implicite'] },

  // === MAD-SPECIFIC ===
  { slug: 'panier-bkam', term: 'Panier BKAM 60/40', shortFr: 'Bask reference: 60% EUR + 40% USD, K=10.49.', shortEn: 'Basket ref: 60% EUR + 40% USD, K=10.49.', longFr: 'Le panier de référence BKAM est composé à 60% d\'EUR et 40% d\'USD, avec un coefficient K = 10.49. Formule : USD/MAD_central = K / (0.60 × EUR/USD + 0.40). Le MAD s\'arrime à ce panier depuis 2018.', longEn: 'The BKAM reference basket is 60% EUR + 40% USD, with K = 10.49. Formula: USD/MAD_central = K / (0.60 × EUR/USD + 0.40). The MAD has been pegged to this basket since 2018.', category: 'mad-specific', related: ['bande-5-pct', 'fixing', 'monia'] },
  { slug: 'bande-5-pct', term: 'Bande de fluctuation ±5%', shortFr: 'Cage réglementaire BKAM: ±5% autour de la parité centrale du panier.', shortEn: 'BKAM regulatory band: ±5% around basket central parity.', longFr: 'Depuis mars 2020 (Phase II), le MAD peut fluctuer ±5% autour de la parité centrale calculée par le panier. En pratique, la fluctuation effective reste dans ±1.5% en 2025-2026.', longEn: 'Since March 2020 (Phase II), the MAD can fluctuate ±5% around the basket central parity. In practice, the effective range stays within ±1.5% in 2025-2026.', category: 'mad-specific', related: ['panier-bkam', 'fixing'] },
  { slug: 'fixing', term: 'Fixing BKAM', shortFr: 'Cours de référence publié à 12:30 et 16:15 (heure Casablanca).', shortEn: 'Reference rate published 12:30 and 16:15 (Casablanca time).', longFr: 'Bank Al-Maghrib publie deux fixings par jour : 12:30 (intraday, milieu de session MIC) et 16:15 (clôture, basé sur les transactions réelles). Le fixing 16:15 est la référence utilisée pour les transactions.', longEn: 'Bank Al-Maghrib publishes two fixings per day: 12:30 (intraday, mid-MIC session) and 16:15 (close, based on actual transactions). The 16:15 fixing is the reference used for transactions.', category: 'mad-specific', related: ['panier-bkam', 'mic-bkam'] },
  { slug: 'mic-bkam', term: 'MIC (Marché Interbancaire de Change)', shortFr: 'Plateforme de change interbancaire BAM. Heures: 8:30-15:30 (Ramadan: 9:15-13:15).', shortEn: 'BAM interbank FX platform. Hours: 8:30-15:30 (Ramadan: 9:15-13:15).', longFr: 'Le MIC est la plateforme où les banques agréées échangent le MAD contre les devises étrangères. Il fonctionne en semaine sauf jours fériés, avec des horaires réduits pendant le Ramadan (UTC+0 au lieu de UTC+1).', longEn: 'The MIC is the platform where licensed banks exchange MAD for foreign currencies. It runs weekdays except holidays, with reduced hours during Ramadan (UTC+0 instead of UTC+1).', category: 'mad-specific', related: ['fixing', 'ramadan-trading-hours'] },
  { slug: 'ramadan-trading-hours', term: 'Heures de marché Ramadan', shortFr: 'MIC réduit pendant Ramadan: 9:15-13:15 au lieu de 8:30-15:30.', shortEn: 'MIC reduced during Ramadan: 9:15-13:15 instead of 8:30-15:30.', longFr: 'Pendant le Ramadan, le Maroc passe en UTC+0 (vs UTC+1 le reste de l\'année). Le MIC adapte ses horaires : 9:15-13:15 au lieu de 8:30-15:30. Le fixing passe à 14:00 au lieu de 16:15.', longEn: 'During Ramadan, Morocco moves to UTC+0 (vs UTC+1 the rest of the year). The MIC adjusts: 9:15-13:15 instead of 8:30-15:30. The fixing moves to 14:00 instead of 16:15.', category: 'mad-specific', related: ['mic-bkam', 'fixing'] },
  { slug: 'uma-convention', term: 'Convention UMA', shortFr: 'Taux de change bilatéral UMA (TND, DZD, LYD) fixé par la convention.', shortEn: 'Bilateral UMA FX rate (TND, DZD, LYD) set by convention.', longFr: 'Les taux de change TND, DZD, LYD contre MAD ne sont pas déterminés par le marché mais par la Convention UMA (Union du Maghreb Arabe) de paiement bilatéral. Ils sont relativement stables mais déconnectés des taux de marché.', longEn: 'TND, DZD, LYD exchange rates against MAD are not market-determined but set by the UMA (Arab Maghreb Union) bilateral payment convention. They are relatively stable but disconnected from market rates.', category: 'mad-specific', related: ['bkam'] },
  { slug: 'monia', term: 'MONIA (Moroccan Overnight Index Average)', shortFr: 'Taux interbancaire overnight de référence, calculé par BAM.', shortEn: 'Overnight interbank reference rate, calculated by BAM.', longFr: 'Le MONIA est l\'équivalent marocain du SOFR (USD) ou de l\'€STR (EUR). C\'est le taux overnight moyen des transactions interbancaires non garanties. Il sert de référence pour le pricing des produits monétaires.', longEn: 'MONIA is the Moroccan equivalent of SOFR (USD) or €STR (EUR). It is the average overnight rate of unsecured interbank transactions. It serves as a reference for money-market product pricing.', category: 'mad-specific', related: ['politique-monetaire-bam', 'panier-bkam'] },
  { slug: 'convertibilite', term: 'Convertibilité du MAD', shortFr: 'Pleine convertibilité du compte courant depuis 1993, capital depuis 2018.', shortEn: 'Full current account convertibility since 1993, capital since 2018.', longFr: 'Le MAD a une pleine convertibilité de compte courant depuis 1993 (conformément aux statuts du FMI). La convertibilité du compte capital a été adoptée en 2018 (Phase II), avec un élargissement progressif des bandes.', longEn: 'The MAD has full current account convertibility since 1993 (per IMF Articles of Agreement). Capital account convertibility was adopted in 2018 (Phase II), with progressive band widening.', category: 'mad-specific', related: ['panier-bkam', 'bande-5-pct'] },
  { slug: 'phase-ii-2018', term: 'Phase II (2018)', shortFr: 'Élargissement progressif des bandes de fluctuation à ±5%.', shortEn: 'Progressive widening of fluctuation bands to ±5%.', longFr: 'Phase II du régime de change marocain : depuis 2018, les bandes de fluctuation s\'élargissent progressivement. Mars 2020 = ±5%. Phase III prévue pour 2027+ (élargissement à ±10% selon FMI).', longEn: 'Phase II of the Moroccan FX regime: since 2018, fluctuation bands widen progressively. March 2020 = ±5%. Phase III planned for 2027+ (widening to ±10% per IMF).', category: 'mad-specific', related: ['bande-5-pct', 'convertibilite'] },
  { slug: 'billet-200', term: 'Billet 200 MAD', shortFr: 'Plus grosse coupure MAD, émission BAM depuis 2002.', shortEn: 'Largest MAD denomination, BAM issuance since 2002.', longFr: 'Le billet de 200 MAD est la plus grosse coupure en circulation. Il est émis par Bank Al-Maghrib depuis 2002. La série actuelle (Type 2013) intègre des éléments de sécurité modernes (fil de sécurité, encre optiquement variable).', longEn: 'The 200 MAD banknote is the largest denomination in circulation. Issued by Bank Al-Maghrib since 2002. The current series (Type 2013) features modern security elements (security thread, optically variable ink).', category: 'mad-specific', related: ['billet'] },

  // === REGULATION OC ===
  { slug: 'circ-oc-01-2024', term: 'Circ. OC 01/2024', shortFr: 'Circulaire Office des Changes 2024 sur les couvertures de change autorisées.', shortEn: 'OC 2024 circular on authorized FX hedging instruments.', longFr: 'La Circ. OC 01/2024 encadre les instruments de couverture de change pour les entreprises résidentes. Autorisés : forwards, FX swaps, options vanilla. INTERDITS : options exotiques, binaires, produits à levier, options digitales.', longEn: 'Circ. OC 01/2024 regulates FX hedging instruments for Moroccan-resident corporates. Authorized: forwards, FX swaps, vanilla options. PROHIBITED: exotic options, binaries, leveraged products, digital options.', category: 'regulation-oc', related: ['forward', 'option-vanilla', 'option-exotique'] },
  { slug: 'igoc', term: 'IGOC (Instruction Générale des Opérations de Change)', shortFr: 'Cadre réglementaire général des opérations de change au Maroc.', shortEn: 'General regulatory framework for FX operations in Morocco.', longFr: 'L\'IGOC est l\'instruction de référence publiée par Bank Al-Maghrib qui fixe les règles relatives aux opérations de change, transferts de fonds, et investissements à l\'étranger. Émise en 2017, mise à jour 2024.', longEn: 'The IGOC is the reference instruction published by Bank Al-Maghrib setting rules for FX operations, fund transfers, and foreign investments. Issued 2017, updated 2024.', category: 'regulation-oc', related: ['circ-oc-01-2024', 'office-des-changes'] },
  { slug: 'office-des-changes', term: 'Office des Changes (OC)', shortFr: 'Autorité marocaine de régulation des changes et mouvements de capitaux.', shortEn: 'Moroccan authority regulating FX and capital movements.', longFr: 'L\'Office des Changes est l\'autorité administrative qui contrôle les mouvements de capitaux entre le Maroc et l\'étranger. Il émet circulaires, instructions et communiqués. Il supervise également les déclarations des opérateurs.', longEn: 'The Office des Changes is the administrative authority that controls capital movements between Morocco and abroad. It issues circulars, instructions and communiqués. It also supervises operator declarations.', category: 'regulation-oc', related: ['igoc', 'circ-oc-01-2024'] },
  { slug: 'repatriation-150-jours', term: 'Répatriement 150 jours', shortFr: 'Délai max de rapatriement des recettes d\'exportation: 150 jours.', shortEn: 'Max delay for repatriation of export proceeds: 150 days.', longFr: 'Selon la Circ. 3/2019, les exportateurs marocains doivent rapatrier leurs recettes de change dans un délai de 150 jours suivant l\'expédition. Au-delà, sanctions de 5% par mois de retard.', longEn: 'Per Circ. 3/2019, Moroccan exporters must repatriate their FX proceeds within 150 days of shipment. Beyond that, penalties of 5% per month of delay apply.', category: 'regulation-oc', related: ['circ-exportations', 'igoc'] },
  { slug: 'cpec-cde', term: 'CDE / CPEC', shortFr: 'Compte en Devises Étrangères / Compte Professionnel en Devises.', shortEn: 'Foreign Currency Account / Professional Foreign Currency Account.', longFr: 'Le CDE permet à toute personne physique résidente de détenir jusqu\'à 100% de ses revenus en devises. Le CPEC est réservé aux exportateurs (CA export > 5M MAD/an) et permet de conserver 70% des recettes export en devises.', longEn: 'The CDE allows any resident individual to hold up to 100% of their income in foreign currency. The CPEC is reserved for exporters (export revenue > 5M MAD/year) and allows keeping 70% of export proceeds in FX.', category: 'regulation-oc', related: ['igoc', 'office-des-changes'] },
  { slug: 'allocation-voyage', term: 'Allocation voyage', shortFr: 'Plafond annuel en devises pour voyages: 45 000 MAD/personne.', shortEn: 'Annual FX allowance for travel: 45,000 MAD/person.', longFr: 'La Circ. 2/2019 fixe les allocations en devises pour voyages touristiques (45 000 MAD/an), pèlerinage (25 000 MAD Hajj, 15 000 MAD Omra), soins médicaux (200 000 MAD/an), et études à l\'étranger.', longEn: 'Circ. 2/2019 sets FX allowances for tourist travel (45,000 MAD/yr), pilgrimage (25,000 MAD Hajj, 15,000 MAD Omra), medical care (200,000 MAD/yr), and studies abroad.', category: 'regulation-oc', related: ['igoc'] },
  { slug: 'domiciliation', term: 'Domiciliation bancaire', shortFr: 'Toute importation >50 000 MAD doit être domiciliée auprès d\'une banque.', shortEn: 'Any import >50,000 MAD must be domiciled with a bank.', longFr: 'La domiciliation est l\'obligation pour toute importation de biens dont la valeur dépasse 50 000 MAD de la domicilier auprès d\'une banque agréée avant le dédouanement. La Circ. 2/2012 détaille la procédure.', longEn: 'Domiciliation is the obligation for any goods import exceeding 50,000 MAD to be domiciled with a licensed bank before customs clearance. Circ. 2/2012 details the procedure.', category: 'regulation-oc', related: ['circ-importations'] },
  { slug: 'circ-importations', term: 'Circ. 2/2012 (Importations)', shortFr: 'Cadre réglementaire des paiements d\'importation de biens et services.', shortEn: 'Regulatory framework for goods and services import payments.', longFr: 'La Circ. 2/2012 régit le paiement des importations de biens et services: domiciliation obligatoire, plafonds d\'avances, délais de règlement (120 jours après dédouanement).', longEn: 'Circ. 2/2012 governs import payments for goods and services: mandatory domiciliation, advance caps, payment delays (120 days post-clearance).', category: 'regulation-oc', related: ['domiciliation', 'igoc'] },
  { slug: 'circ-exportations', term: 'Circ. 3/2019 (Exportations)', shortFr: 'Rapatriement obligatoire des recettes d\'exportation sous 150 jours.', shortEn: 'Mandatory repatriation of export proceeds within 150 days.', longFr: 'La Circ. 3/2019 fixe l\'obligation de rapatrier les recettes d\'exportation sous 150 jours (90 jours pour hydrocarbures, 60 jours pour services). 30% doivent être cédés à BAM sous 30 jours.', longEn: 'Circ. 3/2019 mandates repatriation of export proceeds within 150 days (90 for hydrocarbons, 60 for services). 30% must be sold to BAM within 30 days.', category: 'regulation-oc', related: ['repatriation-150-jours'] },
  { slug: 'reporting-pme', term: 'Reporting PME OC', shortFr: 'PME importatrices/exportatrices >500K MAD/mois: déclaration mensuelle.', shortEn: 'Importing/exporting SMEs >500K MAD/month: monthly declaration.', longFr: 'La Circ. OC 01/2024 impose aux PME (CA import/export >500 000 MAD/mois) un reporting mensuel détaillé des flux de change, contreparties, délais de règlement et instruments de couverture utilisés.', longEn: 'Circ. OC 01/2024 requires SMEs (import/export turnover >500,000 MAD/month) to file a detailed monthly report on FX flows, counterparties, payment delays, and hedging instruments used.', category: 'regulation-oc', related: ['circ-oc-01-2024'] },
  { slug: 'loi-19-14', term: 'Loi 19-14', shortFr: 'Loi 2014 criminalisant les infractions de change au Maroc.', shortEn: '2014 law criminalizing FX violations in Morocco.', longFr: 'La Loi 19-14 modifie et complète le Dahir portant loi n° 1-73-318 du 15 Moharrem 1393 (1973) réprimant les infractions à la réglementation des changes. Sanctions: amendes + emprisonnement.', longEn: 'Law 19-14 amends and supplements the Dahir carrying Law 1-73-318 of 15 Moharrem 1393 (1973) punishing violations of FX regulation. Sanctions: fines + imprisonment.', category: 'regulation-oc', related: ['loi-103-12', 'office-des-changes'] },
  { slug: 'loi-103-12', term: 'Loi 103-12', shortFr: 'Loi bancaire marocaine 2014: cadre prudentiel BAM.', shortEn: 'Moroccan banking law 2014: BAM prudential framework.', longFr: 'La Loi 103-12 relative aux établissements de crédit et organismes assimilés pose le cadre prudentiel pour les banques marocaines. BAM Al-Maghrib supervise, contrôle et sanctionne. Ratios: Tier 1 ≥ 9%, solvabilité ≥ 12%.', longEn: 'Law 103-12 on credit institutions and similar bodies sets the prudential framework for Moroccan banks. Bank Al-Maghrib supervises, controls and sanctions. Ratios: Tier 1 ≥ 9%, solvency ≥ 12%.', category: 'regulation-oc', related: ['loi-19-14'] },

  // === RISK MANAGEMENT ===
  { slug: 'risque-transactionnel', term: 'Risque transactionnel', shortFr: 'Exposition au change sur flux commerciaux déjà engagés.', shortEn: 'FX exposure on already-committed commercial flows.', longFr: 'Le risque transactionnel est l\'exposition au change sur des transactions déjà contractées (facture fournisseur ou client signée). Il est certain et quantifiable. Horizon: du booking au paiement.', longEn: 'Transactional risk is FX exposure on already-contracted transactions (signed supplier or client invoice). It is certain and quantifiable. Horizon: from booking to payment.', category: 'risk-management', related: ['risque-economique', 'forward'] },
  { slug: 'risque-economique', term: 'Risque économique', shortFr: 'Exposition au change sur flux prévisionnels (non encore contractés).', shortEn: 'FX exposure on forecasted flows (not yet contracted).', longFr: 'Le risque économique (ou translationnel) est l\'exposition sur des flux prévisionnels (budget, business plan). Il est incertain. Horizon: 1-3 ans. Couverture via options, rolling forwards, ou budget-based hedges.', longEn: 'Economic (or translational) risk is exposure on forecasted flows (budget, business plan). It is uncertain. Horizon: 1-3 years. Hedged via options, rolling forwards, or budget-based hedges.', category: 'risk-management', related: ['risque-transactionnel', 'option-vanilla'] },
  { slug: 'risque-contrepartie', term: 'Risque de contrepartie', shortFr: 'Risque que la contrepartie ne honore pas ses engagements.', shortEn: 'Risk that the counterparty does not honor its commitments.', longFr: 'Le risque de contrepartie est le risque qu\'une banque ou un client ne respecte pas ses obligations contractuelles. Mitigé par les CSA (Credit Support Annex), les appels de marge, et les limites de crédit.', longEn: 'Counterparty risk is the risk that a bank or client does not meet its contractual obligations. Mitigated by CSAs (Credit Support Annex), margin calls, and credit limits.', category: 'risk-management', related: ['risque-transactionnel'] },
  { slug: 'var', term: 'VaR (Value at Risk)', shortFr: 'Perte maximale sur un horizon donné, avec un niveau de confiance.', shortEn: 'Max loss over a given horizon, at a confidence level.', longFr: 'La Value at Risk est la perte maximale potentielle sur un horizon donné (1j, 10j, 1an) avec un niveau de confiance donné (95%, 99%). Utilisée pour le reporting risk management Bâle III.', longEn: 'Value at Risk is the maximum potential loss over a given horizon (1d, 10d, 1y) at a given confidence level (95%, 99%). Used for Basel III risk management reporting.', category: 'risk-management', related: ['risque-transactionnel'] },
  { slug: 'policy-couverture', term: 'Politique de couverture', shortFr: 'Document interne définissant la stratégie FX de l\'entreprise.', shortEn: 'Internal document defining the corporate FX hedging strategy.', longFr: 'Une politique de couverture FX documente: exposition admissible (%), instruments autorisés, plafonds par contrepartie, reporting, gouvernance. Recommandée par l\'OC 01/2024 pour les PME > 5M MAD/mois d\'exposition.', longEn: 'An FX hedging policy documents: allowable exposure (%), authorized instruments, counterparty limits, reporting, governance. Recommended by OC 01/2024 for SMEs > 5M MAD/month exposure.', category: 'risk-management', related: ['circ-oc-01-2024'] },
  { slug: 'stop-loss', term: 'Stop-loss FX', shortFr: 'Ordre conditionnel pour fermer une position si la perte dépasse un seuil.', shortEn: 'Conditional order to close a position if loss exceeds a threshold.', longFr: 'Un stop-loss FX est un seuil de perte maximal prédéfini. Si le marché le touche, la position est automatiquement fermée. Limite les pertes mais peut sortir trop tôt en cas de bruit.', longEn: 'A FX stop-loss is a predefined max-loss threshold. If the market hits it, the position is automatically closed. Limits losses but may exit too early on noise.', category: 'risk-management', related: ['var', 'risque-transactionnel'] },

  // === BANKING MOROCCO ===
  { slug: 'attijariwafa', term: 'Attijariwafa Bank', shortFr: '1ère banque marocaine par les actifs. Cotée à Casablanca.', shortEn: '#1 Moroccan bank by assets. Listed in Casablanca.', longFr: 'Attijariwafa Bank est la première banque marocaine par les actifs (~600 Mds MAD). Issue de la fusion BCM/Wafa Bank en 2003. Cotée à la Bourse de Casablanca, présente dans 25+ pays africains.', longEn: 'Attijariwafa Bank is the leading Moroccan bank by assets (~600B MAD). Born from the 2003 BCM/Wafa Bank merger. Listed on the Casablanca Stock Exchange, present in 25+ African countries.', category: 'banking-morocco', related: ['banque-maroc', 'banque-populaire'] },
  { slug: 'banque-populaire', term: 'Banque Populaire du Maroc', shortFr: '2ème banque marocaine, réseau coopératif dense.', shortEn: '#2 Moroccan bank, dense cooperative network.', longFr: 'Le Groupe Banque Populaire (BCP) est la 2ème banque marocaine. Réseau de caisses régionales issues du mouvement coopératif. Très présente dans la banque de détail, l\'agriculture, et la diaspora marocaine en Europe.', longEn: 'Banque Populaire Group (BCP) is the 2nd Moroccan bank. Network of regional cooperatives. Strong presence in retail, agriculture, and Moroccan diaspora in Europe.', category: 'banking-morocco', related: ['attijariwafa'] },
  { slug: 'bmce', term: 'BMCE Bank (Bank of Africa)', shortFr: '3ème banque marocaine, présence forte en Afrique subsaharienne.', shortEn: '#3 Moroccan bank, strong SSA presence.', longFr: 'BMCE Bank of Africa est la 3ème banque marocaine (renommée Bank of Africa en 2020). Très active en Afrique subsaharienne, leader du marché marocain des transferts MRE (Marocains Résidant à l\'Étranger).', longEn: 'BMCE Bank of Africa is the 3rd Moroccan bank (renamed Bank of Africa in 2020). Very active in sub-Saharan Africa, leader in the Moroccan market for MRE (Moroccans Residing Abroad) transfers.', category: 'banking-morocco', related: ['attijariwafa', 'mre'] },
  { slug: 'cih', term: 'CIH Bank', shortFr: '4ème banque marocaine, spécialiste de l\'immobilier.', shortEn: '#4 Moroccan bank, real-estate specialist.', longFr: 'CIH Bank (Crédit Immobilier et Hôtelier) est la 4ème banque marocaine. Spécialisée historiquement dans le financement immobilier et hôtelier, elle a diversifié vers la banque de détail, corporate, et islamique.', longEn: 'CIH Bank (Real Estate and Hotel Credit) is the 4th Moroccan bank. Historically specialized in real estate and hotel financing, it has diversified into retail, corporate, and Islamic banking.', category: 'banking-morocco', related: ['banque-maroc'] },
  { slug: 'sg-maroc', term: 'Société Générale Maroc', shortFr: 'Filiale du groupe Société Générale, banque universelle.', shortEn: 'Subsidiary of Société Générale group, universal bank.', longFr: 'Société Générale Maroc est la filiale marocaine du groupe français Société Générale. Banque universelle, présente dans la banque de détail, corporate, investment banking.', longEn: 'Société Générale Maroc is the Moroccan subsidiary of the French Société Générale group. Universal bank, present in retail, corporate, and investment banking.', category: 'banking-morocco', related: ['banque-maroc'] },
  { slug: 'mre', term: 'MRE (Marocains Résidant à l\'Étranger)', shortFr: 'Diaspora marocaine: ~5M personnes, transferts = 7% du PIB.', shortEn: 'Moroccan diaspora: ~5M people, transfers = 7% of GDP.', longFr: 'Les MRE (Marocains Résidant à l\'Étranger) représentent une communauté de ~5 millions de personnes, principalement en Europe. Leurs transferts de fonds vers le Maroc atteignent ~7% du PIB, un record mondial.', longEn: 'MREs (Moroccans Residing Abroad) represent a community of ~5 million people, mainly in Europe. Their remittances to Morocco reach ~7% of GDP, a world record.', category: 'banking-morocco', related: ['bmce'] },

  // === MONETARY POLICY ===
  { slug: 'taux-directeur-bam', term: 'Taux directeur BAM', shortFr: 'Taux de la politique monétaire BAM: 2.75% en 2025.', shortEn: 'BAM policy rate: 2.75% in 2025.', longFr: 'Le taux directeur de Bank Al-Maghrib est l\'instrument principal de la politique monétaire marocaine. Il a évolué: 3.00% (2024) → 2.75% (2025). Il sert de référence pour le MONIA, les facilités permanentes, et la courbe des taux.', longEn: 'The Bank Al-Maghrib policy rate is the main instrument of Moroccan monetary policy. It evolved: 3.00% (2024) → 2.75% (2025). It serves as the reference for MONIA, standing facilities, and the yield curve.', category: 'monetary-policy', related: ['monia', 'reserve-bancaire'] },
  { slug: 'reserve-bancaire', term: 'Réserves bancaires', shortFr: 'Ratio de réserves obligatoires BAM: 3% des dépôts à vue.', shortEn: 'BAM reserve requirement ratio: 3% of demand deposits.', longFr: 'Le coefficient de réserves obligatoires appliqué par Bank Al-Maghrib est de 3% sur les dépôts à vue et comptes courants. Les banques doivent déposer ce montant à BAM, non rémunéré.', longEn: 'The reserve requirement ratio applied by Bank Al-Maghrib is 3% on demand deposits and current accounts. Banks must deposit this amount with BAM, non-interest bearing.', category: 'monetary-policy', related: ['taux-directeur-bam', 'monia'] },
  { slug: 'reserve-change', term: 'Réserves de change BAM', shortFr: 'Encours BAM en devises: ~36 Mds USD (2025).', shortEn: 'BAM FX reserves: ~36B USD (2025).', longFr: 'Les réserves de change de BAM s\'élèvent à environ 36 milliards USD (2025), soit ~4.2 mois d\'importations. La cible IMF est 5+ mois. La BAM intervient pour défendre la parité panier.', longEn: 'BAM FX reserves are around 36 billion USD (2025), or ~4.2 months of imports. The IMF target is 5+ months. BAM intervenes to defend the basket parity.', category: 'monetary-policy', related: ['taux-directeur-bam', 'panier-bkam'] },
  { slug: 'facilites-permanentes', term: 'Facilités permanentes', shortFr: 'BAM refinance/place banques overnight via 2 facilités.', shortEn: 'BAM lends/deposits banks overnight via 2 facilities.', longFr: 'BAM opère deux facilités permanentes: la facilité de prêt marginal (taux = taux directeur + 2%, plafonné) et la facilité de dépôt (taux = taux directeur − 2%, plancher). Elles encadrent le MONIA.', longEn: 'BAM operates two standing facilities: the marginal lending facility (rate = policy rate + 2%, capped) and the deposit facility (rate = policy rate − 2%, floored). They frame the MONIA.', category: 'monetary-policy', related: ['monia', 'taux-directeur-bam'] },
  { slug: 'open-market', term: 'Opérations d\'open market BAM', shortFr: 'Adjudications 7j/14j/28j, repo inverse, swaps de change.', shortEn: '7d/14d/28d tenders, reverse repo, FX swaps.', longFr: 'BAM intervient sur le marché monétaire via des adjudications de pensions livrées (7j, 14j, 28j), des prises en pension (repos inverses), et des swaps de change. Ces opérations absorbent ou injectent de la liquidité.', longEn: 'BAM operates on the money market via repo tenders (7d, 14d, 28d), reverse repos, and FX swaps. These operations absorb or inject liquidity.', category: 'monetary-policy', related: ['monia', 'taux-directeur-bam'] },

  // === INSTRUMENTS ===
  { slug: 'ndf-instrument', term: 'NDF (instrument)', shortFr: 'Forward cash-settled sans livraison, jadis pour MAD pré-2018.', shortEn: 'Cash-settled forward without delivery, formerly for MAD pre-2018.', longFr: 'Le NDF (Non-Deliverable Forward) est un forward sur devises non convertibles qui se règle par différentiel cash. Pour le MAD, les NDF sont devenus obsolètes depuis la convertibilité du compte capital (2018).', longEn: 'An NDF (Non-Deliverable Forward) is a forward on non-convertible currencies settled by cash differential. For MAD, NDFs became obsolete after capital account convertibility (2018).', category: 'instruments', related: ['forward', 'convertibilite'] },
  { slug: 'swap-currency', term: 'Swap cambiste (FX swap)', shortFr: 'Achat spot + vente forward simultanés, ou inverse.', shortEn: 'Buy spot + sell forward simultaneously, or reverse.', longFr: 'Le swap cambiste est l\'échange simultané d\'une devise contre une autre à deux dates différentes. Utilisé par les banques pour la gestion de trésorerie, par les entreprises pour le roulement de position, et par les BC pour la politique monétaire.', longEn: 'An FX swap is the simultaneous exchange of one currency for another at two different dates. Used by banks for treasury management, by corporates for position rolling, and by central banks for monetary policy.', category: 'instruments', related: ['forward', 'swap'] },
  { slug: 'cross-currency-swap', term: 'Cross-currency swap (CCS)', shortFr: 'Swap de taux + change sur plusieurs années. Échange de principal.', shortEn: 'Interest rate + FX swap over multiple years. Principal exchange.', longFr: 'Le CCS (Cross-Currency Swap) combine un swap de taux et un swap de change. Il y a échange de principal initial et final, plus échanges de coupons périodiques. Maturités 2-30 ans typiques.', longEn: 'A CCS (Cross-Currency Swap) combines an interest rate swap and an FX swap. There is initial and final principal exchange, plus periodic coupon exchanges. Maturities 2-30 years typical.', category: 'instruments', related: ['swap', 'xcs'] },
  { slug: 'swap-change-base', term: 'Basis swap', shortFr: 'Swap de change à 3M/6M, benchmark sur points de swap.', shortEn: '3M/6M FX swap, benchmarked on swap points.', longFr: 'Le basis swap (FX swap) est la forme la plus liquide du marché des changes. C\'est l\'échange d\'une devise contre une autre à deux dates (typiquement spot vs 3M), avec réversion implicite au taux forward. Le différentiel (basis) reflète la liquidité interbancaire.', longEn: 'The basis swap (FX swap) is the most liquid form of FX market. It is the exchange of one currency for another at two dates (typically spot vs 3M), with implicit reversion at the forward rate. The differential (basis) reflects interbank liquidity.', category: 'instruments', related: ['swap', 'xcs'] },
  { slug: 'ccs-mad', term: 'CCS MAD', shortFr: 'Cross-currency swap en MAD: rare, principalement avec Trésor.', shortEn: 'MAD cross-currency swap: rare, mainly with Treasury.', longFr: 'Les CCS en MAD sont rares en raison de la nature gérée de la devise. Le Trésor marocain émet occasionnellement des eurobonds swapés en MAD. Les banques multilatérales utilisent aussi des CCS pour le financement de projets.', longEn: 'CCS in MAD are rare due to the managed nature of the currency. The Moroccan Treasury occasionally issues eurobonds swapped into MAD. Multilateral banks also use CCS for project financing.', category: 'instruments', related: ['cross-currency-swap'] },
];

// Helper functions
export function getTermBySlug(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.slug === slug);
}

export function getRelatedTerms(slug: string): GlossaryTerm[] {
  const term = getTermBySlug(slug);
  if (!term) return [];
  return term.related.map(getTermBySlug).filter((t): t is GlossaryTerm => Boolean(t));
}

export function getTermsByCategory(category: GlossaryCategory): GlossaryTerm[] {
  return GLOSSARY.filter((t) => t.category === category);
}

export function searchTerms(query: string): GlossaryTerm[] {
  const q = query.toLowerCase().trim();
  if (!q) return GLOSSARY;
  return GLOSSARY.filter(
    (t) =>
      t.term.toLowerCase().includes(q) ||
      t.shortFr.toLowerCase().includes(q) ||
      t.shortEn.toLowerCase().includes(q) ||
      t.longFr.toLowerCase().includes(q),
  );
}
